language: node_js
node_js: stable

#cache
cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - 3075822809@qq.com
    on_success: always
    on_failure: always

# S: Build Lifecycle
install:
  - npm install
  - gem install travis
  - travis logs
  - travis show


before_script:
  - export TZ='Asia/Shanghai'
  - npm install -g gulp 
  #- chmod +x travis.sh

script:
  - hexo g
  - gulp 

after_success:
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - echo -e "$TRAVIS_TEST_RESULT" >> README.md
  - cat README.md
#  - git init
#  - git config user.name "shenliyang"
#  - git config user.email ""
#  - git add .
#  - git commit -m "Build by Travis CI at `date +"%Y-%m-%d\ %H:%M:%S"`"
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/shenliyang/shenliyang.github.io.git

