language: node_js
node_js: stable

#cache
cache:
  directories:
    - "node_modules"

# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g gulp 

script:
  - hexo g
  - gulp 
  - touch README.md
  - echo "你要追加的内容" >> README.md
  - cat README.md


after_script:
  - cd ./public
  - git init
  - git config user.name "shenliyang"
  - git config user.email ""
  - git add .
  - git commit -m "Build by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/shenliyang/shenliyang.github.io.git

